name: ci
on:
  push:
    branches:
      - master

  pull_request:
    branches:
      - master

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 16
      - uses: actions/cache@v2
        id: yarn-cache
        with:
          path: |
            node_modules
            ~/.cache/ms-playwright
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
      - name: Install
        run: yarn
      - name: Run tests
        run: yarn test
      - name: Lint
        run: yarn lint
      - name: Prettier
        run: yarn run prettier -c .
