name: ci
on:
  push:
    branches:
      - master

  pull_request:
    branches:
      - master

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: ./.github/actions/setup

      - name: Run tests
        run: yarn test

      - name: Lint
        run: yarn lint

      - name: Build
        run: yarn build
