name: Release

on:
  push:
    branches:
      - master

jobs:
  version:
    runs-on: ubuntu-latest
    steps:
      - uses: googleapis/release-please-action@v4
        id: release-please
        with:
          release-type: node
    outputs:
      release_created: ${{ steps.release-please.outputs.release_created }}

  publish:
    runs-on: ubuntu-latest
    needs: [version]
    if: ${{ needs.version.outputs.release_created }}
    steps:
      - uses: actions/checkout@v4

      - uses: ./.github/actions/setup

      - name: Build
        run: yarn run build

      - name: Check NPM_TOKEN
        run: |
          if [ -z "$NPM_TOKEN" ]; then
            echo "NPM_TOKEN is not set"
            exit 1
          else
            echo "NPM_TOKEN is set"
          fi
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Publish to NPM
        run: yarn publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
